{{- if or .Values.nodeAgent.monitors .Values.nodeAgent.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eks-node-monitoring-agent.fullname" . }}-monitor-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-node-monitoring-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- with .Values.nodeAgent.monitors }}
    monitors:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.nodeAgent.metrics.enabled }}
    metrics:
      enabled: true
      address: ":{{ .Values.nodeAgent.metrics.port }}"
      {{- with .Values.nodeAgent.metrics.collectors }}
      collectors:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeAgent.metrics.extraArgs }}
      extraArgs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      includeExporterMetrics: {{ .Values.nodeAgent.metrics.includeExporterMetrics }}
    {{- end }}
{{- end }}
