package hostmetrics

// PROVENANCE
//   derived from: node_exporter/collector/netstat_linux.go
//   upstream commit: b401dcfc667cee0a5d29232bab51a8ce1c58ec07
//   upstream copyright: 2015 The Prometheus Authors, Apache-2.0
//
// FIXES A FOURTH UPSTREAM CRASH, found by adversarial testing rather than
// observed in production. Upstream's parseNetStats does:
//
//	nameParts := strings.Split(scanner.Text(), " ")
//	scanner.Scan()
//	valueParts := strings.Split(scanner.Text(), " ")
//	protocol := nameParts[0][:len(nameParts[0])-1]   // <-- strips trailing ":"
//
// On an EMPTY line, nameParts[0] is "" and the slice expression becomes [:-1],
// which panics with "slice bounds out of range [:-1]". Verified against a verbatim
// copy of upstream's function:
//
//	well-formed            ok
//	trailing empty line    PANIC: slice bounds out of range [:-1]
//	leading empty line     PANIC
//	empty line in middle   PANIC
//	blank-only file        PANIC
//
// HONEST SEVERITY: unlike netclass #1915, this is NOT reachable on a healthy
// kernel. /proc/net/netstat and /proc/net/snmp are generated by the kernel in
// strict name-line/value-line pairs with no blank lines (confirmed on the live
// node: 6 and 12 lines, zero blank, both even). So this is a robustness gap, not a
// live-impacting bug, and it is recorded as such rather than claimed as a field
// fix. It is worth fixing anyway because the cost is three lines, the collector is
// parsing a file whose format it does not control, and a panic here would take the
// scrape down rather than degrade it.
//
// Also note upstream returns an ERROR from Update on an unparseable value, which
// discards every already-collected protocol. Here a bad value skips that one field
// and the rest are still reported, on the same reasoning as netclass: partial data
// beats no data.
//
// SCOPE. --collector.netstat.fields is not wired to a flag (this package has no
// flag layer); the default filter is upstream's, verbatim. That default is what
// keeps this collector to ~60 series instead of the ~600 the raw files contain.

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"maps"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/prometheus/client_golang/prometheus"
)

const netStatsSubsystem = "netstat"

// defNetStatFields is upstream's --collector.netstat.fields default, verbatim.
//
// This is a curated allowlist, not a convenience: /proc/net/{netstat,snmp,snmp6}
// together expose several hundred counters, and this pattern selects the ~60 that
// are actually actionable. Widening it is a cardinality decision, not a coverage
// improvement.
const defNetStatFields = "^(.*_(InErrors|InErrs)|Ip_Forwarding|Ip(6|Ext)_(InOctets|OutOctets)|" +
	"Icmp6?_(InMsgs|OutMsgs)|TcpExt_(Listen.*|Syncookies.*|TCPSynRetrans|TCPTimeouts|TCPOFOQueue|TCPRcvQDrop)|" +
	"Tcp_(ActiveOpens|InSegs|OutSegs|OutRsts|PassiveOpens|RetransSegs|CurrEstab)|" +
	"Udp6?_(InDatagrams|OutDatagrams|NoPorts|RcvbufErrors|SndbufErrors))$"

func init() {
	register("netstat", true, newNetStatCollector)
}

type netStatCollector struct {
	logger       *slog.Logger
	paths        Paths
	fieldPattern *regexp.Regexp
}

func newNetStatCollector(logger *slog.Logger, paths Paths) (Collector, error) {
	return newNetStatCollectorWithFields(logger, paths, defNetStatFields)
}

// newNetStatCollectorWithFields is split out so the invalid-pattern branch is
// reachable from a test, and so the field filter can be wired to a chart value
// later without restructuring.
func newNetStatCollectorWithFields(logger *slog.Logger, paths Paths, fields string) (Collector, error) {
	pattern, err := regexp.Compile(fields)
	if err != nil {
		return nil, fmt.Errorf("invalid netstat field pattern %q: %w", fields, err)
	}
	return &netStatCollector{logger: logger, paths: paths, fieldPattern: pattern}, nil
}

func (c *netStatCollector) Update(ch chan<- prometheus.Metric) error {
	netStats, err := readNetStats(c.paths.procPath("net", "netstat"))
	if err != nil {
		return fmt.Errorf("couldn't get netstats: %w", err)
	}
	snmpStats, err := readNetStats(c.paths.procPath("net", "snmp"))
	if err != nil {
		return fmt.Errorf("couldn't get SNMP stats: %w", err)
	}
	snmp6Stats, err := readSNMP6Stats(c.paths.procPath("net", "snmp6"))
	if err != nil {
		return fmt.Errorf("couldn't get SNMP6 stats: %w", err)
	}

	// Keys are unique across the three files for this use case, so a plain merge is
	// safe. Order matters only if that ever stops being true.
	maps.Copy(netStats, snmpStats)
	maps.Copy(netStats, snmp6Stats)

	for protocol, protocolStats := range netStats {
		for name, value := range protocolStats {
			key := protocol + "_" + name
			// Filter BEFORE parsing: the vast majority of fields are excluded, and
			// parsing them only to discard them is wasted work on every scrape.
			// (Upstream parses first, then filters.)
			if !c.fieldPattern.MatchString(key) {
				continue
			}
			v, err := strconv.ParseFloat(value, 64)
			if err != nil {
				// Upstream returns an error here, which discards every protocol
				// already collected. Skip just this field instead.
				c.logger.Debug("invalid value in netstats, skipping field",
					"key", key, "value", value, "err", err)
				continue
			}
			ch <- prometheus.MustNewConstMetric(
				prometheus.NewDesc(
					prometheus.BuildFQName(namespace, netStatsSubsystem, key),
					fmt.Sprintf("Statistic %s.", protocol+name),
					nil, nil,
				),
				// Untyped, matching upstream: these counters are a mix of
				// cumulative counts and instantaneous gauges (Tcp_CurrEstab is a
				// gauge) and upstream does not distinguish them. Typing them all as
				// counters would make rate() lie about CurrEstab.
				prometheus.UntypedValue, v,
			)
		}
	}
	return nil
}

// readNetStats parses /proc/net/netstat or /proc/net/snmp.
//
// Format is alternating name and value lines:
//
//	TcpExt: SyncookiesSent SyncookiesRecv ...
//	TcpExt: 0 0 ...
func readNetStats(fileName string) (map[string]map[string]string, error) {
	file, err := os.Open(fileName)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	return parseNetStats(file, fileName)
}

func parseNetStats(r io.Reader, fileName string) (map[string]map[string]string, error) {
	netStats := map[string]map[string]string{}
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		nameLine := scanner.Text()

		// THE FIX. Upstream does nameParts[0][:len(nameParts[0])-1] to strip the
		// trailing ":", which panics with "slice bounds out of range [:-1]" when the
		// line is empty. Skipping blank lines makes the parser tolerant of a file
		// shape it does not control.
		if strings.TrimSpace(nameLine) == "" {
			continue
		}

		if !scanner.Scan() {
			// A name line with no value line. Upstream reaches the field-count check
			// with valueParts from an empty string and reports a count mismatch;
			// this says what actually happened.
			return nil, fmt.Errorf("%s: header line %q has no matching value line", fileName, nameLine)
		}
		valueLine := scanner.Text()

		nameParts := strings.Split(nameLine, " ")
		valueParts := strings.Split(valueLine, " ")

		// A protocol label must end in ":". Without this check a line that is
		// non-empty but malformed still truncates its last character, silently
		// producing metrics under a wrong protocol name.
		if !strings.HasSuffix(nameParts[0], ":") {
			return nil, fmt.Errorf("%s: malformed header line %q, expected a protocol label ending in ':'",
				fileName, nameLine)
		}
		protocol := strings.TrimSuffix(nameParts[0], ":")

		if len(nameParts) != len(valueParts) {
			return nil, fmt.Errorf("%s: field count mismatch for protocol %s: %d names, %d values",
				fileName, protocol, len(nameParts)-1, len(valueParts)-1)
		}

		if netStats[protocol] == nil {
			netStats[protocol] = map[string]string{}
		}
		for i := 1; i < len(nameParts); i++ {
			netStats[protocol][nameParts[i]] = valueParts[i]
		}
	}

	return netStats, scanner.Err()
}

// readSNMP6Stats parses /proc/net/snmp6, which has a different shape: one
// "NameValue" pair per line rather than paired header and value lines.
func readSNMP6Stats(fileName string) (map[string]map[string]string, error) {
	file, err := os.Open(fileName)
	if err != nil {
		// Absent when IPv6 is disabled in the kernel. Not an error: the IPv6
		// metrics are simply not reported.
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	defer file.Close()
	return parseSNMP6Stats(file)
}

func parseSNMP6Stats(r io.Reader) (map[string]map[string]string, error) {
	netStats := map[string]map[string]string{}
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		stat := strings.Fields(scanner.Text())
		if len(stat) < 2 {
			continue
		}
		// The protocol name is everything up to and including the "6", so
		// "Ip6InOctets" splits into protocol "Ip6" and name "InOctets". A line with
		// no "6" is skipped, matching upstream, because it cannot be attributed to
		// an IPv6 protocol.
		sixIndex := strings.Index(stat[0], "6")
		if sixIndex == -1 {
			continue
		}
		protocol := stat[0][:sixIndex+1]
		name := stat[0][sixIndex+1:]
		if netStats[protocol] == nil {
			netStats[protocol] = map[string]string{}
		}
		netStats[protocol][name] = stat[1]
	}

	return netStats, scanner.Err()
}
